spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boot_template?characterEncoding=utf-8&serverTimezone=UTC
    hikari:
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user
server:
  port: 9090
